In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [10]:
df = pd.read_csv('/content/CAR DETAILS FROM CAR DEKHO.csv')

In [11]:
df.head(8)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner

In [12]:
df.tail(8)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
4332,Mahindra Scorpio S2 7 Seater,2015,750000,120000,Diesel,Individual,Manual,First Owner
4333,Maruti Ritz VDi,2012,225000,90000,Diesel,Individual,Manual,Second Owner
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [14]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [15]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [16]:
print(df.columns.tolist())

['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']

In [17]:
df.duplicated().sum()

np.int64(763)

In [18]:
df.columns = df.columns.str.strip().str.lower()

In [19]:
df['car_age'] = 2025 - df['year']

In [20]:
df.drop('year', axis=1, inplace=True)

In [21]:
if 'name' in df.columns:
    df.drop('name', axis=1, inplace=True)

In [22]:
df = pd.get_dummies(df,drop_first=True)

In [23]:
print(df.head())

   selling_price  km_driven  car_age  fuel_Diesel  fuel_Electric  fuel_LPG  \
0          60000      70000       18        False          False     False
1         135000      50000       18        False          False     False
2         600000     100000       13         True          False     False
3         250000      46000        8        False          False     False
4         450000     141000       11         True          False     False

   fuel_Petrol  seller_type_Individual  seller_type_Trustmark Dealer  \
0         True                    True                         False
1         True                    True                         False
2        False                    True                         False
3         True                    True                         False
4        False                    True                         False

   transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                 True                       False               False
1                 True                       False               False
2                 True                       False               False
3                 True                       False               False
4                 True                       False                True

   owner_Test Drive Car  owner_Third Owner
0                 False              False
1                 False              False
2                 False              False
3                 False              False
4                 False              False

In [24]:
print(df.columns)

Index(['selling_price', 'km_driven', 'car_age', 'fuel_Diesel', 'fuel_Electric',
       'fuel_LPG', 'fuel_Petrol', 'seller_type_Individual',
       'seller_type_Trustmark Dealer', 'transmission_Manual',
       'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Test Drive Car', 'owner_Third Owner'],
      dtype='object')

In [25]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   selling_price                 4340 non-null   int64
 1   km_driven                     4340 non-null   int64
 2   car_age                       4340 non-null   int64
 3   fuel_Diesel                   4340 non-null   bool
 4   fuel_Electric                 4340 non-null   bool
 5   fuel_LPG                      4340 non-null   bool
 6   fuel_Petrol                   4340 non-null   bool
 7   seller_type_Individual        4340 non-null   bool
 8   seller_type_Trustmark Dealer  4340 non-null   bool
 9   transmission_Manual           4340 non-null   bool
 10  owner_Fourth & Above Owner    4340 non-null   bool
 11  owner_Second Owner            4340 non-null   bool
 12  owner_Test Drive Car          4340 non-null   bool
 13  owner_Third Owner             4340 non-null   bool
dtypes: bool(11), int64(3)
memory usage: 148.5 KB
None

In [26]:
print(df.columns.tolist())

['selling_price', 'km_driven', 'car_age', 'fuel_Diesel', 'fuel_Electric', 'fuel_LPG', 'fuel_Petrol', 'seller_type_Individual', 'seller_type_Trustmark Dealer', 'transmission_Manual', 'owner_Fourth & Above Owner', 'owner_Second Owner', 'owner_Test Drive Car', 'owner_Third Owner']

In [27]:
X = df.drop('selling_price', axis=1)
y = df['selling_price']
print("X shape:",X.shape)
print("y shape:",y.shape)

X shape: (4340, 13)
y shape: (4340,)

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
print("Training set:",X_train.shape)
print("Testing set:",X_test.shape)

Training set: (3472, 13)
Testing set: (868, 13)

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
print("Predicted values:", y_pred[:5])
print("Actual values:", y_test[:5])

# Evaluation
r2 = r2_score(y_test, y_pred)
mae = mean_squared_error(y_test, y_pred)
print("R-squared:", r2)
print("Mean Absolute Error:", mae)

Predicted values: [ 429791.44395393  504490.85855368   60211.1711833   475380.44208611
 1519809.14934826]
Actual values: 3978    165000
1448    250000
2664    120000
17      450000
1634    730000
Name: selling_price, dtype: int64
R-squared: 0.4031303601432117
Mean Absolute Error: 182146878750.28098

In [34]:
y_pred = model.predict(X_test)
print("Predicted values:",y_pred[:5])
print("Actual values:",y_test[:5])

Predicted values: [ 429791.44395393  504490.85855368   60211.1711833   475380.44208611
 1519809.14934826]
Actual values: 3978    165000
1448    250000
2664    120000
17      450000
1634    730000
Name: selling_price, dtype: int64

In [35]:
r2 = r2_score(y_test, y_pred)
mae = mean_squared_error(y_test, y_pred)
print("R-squared:", r2)
print("Mean Absolute Error:", mae)

R-squared: 0.4031303601432117
Mean Absolute Error: 182146878750.28098

In [36]:
import joblib


joblib.dump(model, "car_price_model.pkl")


joblib.dump(X.columns.tolist(),'model_columns,pkl')

['model_columns,pkl']

In [37]:
import gradio as gr
import joblib
import numpy as np


model = joblib.load('car_price_model.pkl')
columns = joblib.load('model_columns,pkl')


def predict_price(km_driven, car_age, fuel, seller_type, transmission, owner):

    input_dict = {
        'km_driven': km_driven,
        'car_age': car_age,
        'fuel_Petrol': 1 if fuel == 'Petrol' else 0,
        'seller_type_Individual': 1 if seller_type == 'Individual' else 0,
        'transmission_Manual': 1 if transmission == 'Manual' else 0,
        'owner_Second Owner': 1 if owner == 'Second Owner' else 0,
        'owner_Third Owner': 1 if owner == 'Third Owner' else 0,
    }


    input_array = np.array([input_dict.get(col, 0) for col in columns]).reshape(1, -1)

    price = model.predict(input_array)[0]
    return f"Estimated Selling Price: ₹ {int(price):,}"


demo = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Number(label="Kilometers Driven"),
        gr.Number(label="Car Age (in years)"),
        gr.Dropdown(['Petrol', 'Diesel'], label="Fuel Type"),
        gr.Dropdown(['Dealer', 'Individual'], label="Seller Type"),
        gr.Dropdown(['Manual', 'Automatic'], label="Transmission"),
        gr.Dropdown(['First Owner', 'Second Owner', 'Third Owner'], label="Owner Type"),
    ],
    outputs=gr.Textbox(label="Prediction"),
    title="🚗 Car Price Predictor",
    description="Enter car details to get the estimated selling price"
)


demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://ccff565a44779ad5bc.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)